### PR TITLE
Mod Compatibility API Proposal

### PR DESCRIPTION
**Pull request by Kobata**
Implements an API for mod authors to add the required information for compatibility themselves, instead of it needing to be manually entered into InvTweaksModCompatibility for every mod.

Example of container GUI:

``` java
import invtweaks.api.*;

@ContainerGUI
public class GuiMyContainer extends GuiContainer {
  [...]

  @ContainerGUI.RowSizeCallback
  int getRowSize() {
    return row_size;
  }

  @ContainerGUI.ContainerSectionCallback
  Map<ContainerSection, List<Slot>> getContainerSections() {
    Map<ContainerSection, List<Slot>> sections = new HashMap<>();
    sections.put(ContainerSection.CRAFTING_IN, inventorySlots.subList(0,9));
    sections.put(ContainerSection.CRAFTING_OUT, inventorySlots.subList(9, 10));
    sections.put(ContainerSection.CHEST, inventorySlots.subList(10, 20));
    return sections;
  }
}
```

InventoryGUI is similar, but lacks RowSizeCallback and is intended for non-GuiContainer screens.

### CODE REVIEW

**Comment by mkalam-alami** [comment]
Great idea :)

**Comment by mkalam-alami** [comment]
Hmmm, the pull-request was closed automatically because the `wip` branch doesn't exist anymore, but I still plan on merging this!

**Comment by Kobata** [comment]
Sorry, I read that wrong for a moment, haha. I can rebase and reopen it to the current branch if you haven't manually merged it already.

**Comment by mkalam-alami** [comment]
If you can do that it would be awesome, thanks :+1:

**Comment by Kobata** [comment]
I couldn't find an option to retarget this one so I opened a new version targeting develop as #305

**Pull request closed without merging**
